apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-ydky
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/release-e2e-deploy-tenant/appstudio/dc-metro-map-ydky@sha256:0d40ced0712ffd707b9170193cc56f7ef1b3718f6cc828a961ead9c7662c8f3c
        name: my-nodejs
        resources: {}
status: {}
